source 'https://rubygems.org'

gem 'sinatra'
gem 'pry'

gem 'sinatra'
gem 'sinatra-contrib'

gem 'activerecord'
gem 'pg'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
